labels:
  - pairs:
      app: entities
      app.kubernetes.io/name: entities
    includeSelectors: true
    includeTemplates: true

resources:
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - hpa.yaml
  - pdb.yaml

configMapGenerator:
  - name: entities-appsettings
    files:
      - appsettings.json

generatorOptions:
  disableNameSuffixHash: true
