apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: entities
spec:
  hosts:
    - entities.plantsuite.local
  gateways:
    - istio-ingress/gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 80
            host: entities
