apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: workflows
spec:
  parentRefs:
    - name: gateway
      namespace: istio-ingress
      sectionName: https
  rules:
    - backendRefs:
        - name: workflows
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: workflows-ui
spec:
  parentRefs:
    - name: gateway
      namespace: istio-ingress
      sectionName: https
  rules:
    - backendRefs:
        - name: workflows
          port: 8080
