apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spc
subjects:
  - kind: ServiceAccount
    name: spc
roleRef:
  kind: Role
  name: spc
  apiGroup: rbac.authorization.k8s.io
