namespace: redis
namePrefix: plantsuite-

labels:
  - pairs:  
      app: redis    
    includeSelectors: true

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - statefulset.yaml
  - service-nodes.yaml
  - service.yaml
  - pdb.yaml

configMapGenerator:
  - name: redis
    files:
      - config/redis.conf
      - config/init-config.sh
      - config/init-cluster.sh

secretGenerator:
  - name: redis-env
    envs:
      - .env.secret

generatorOptions:
  disableNameSuffixHash: true