apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - name: client
      port: 6379
      targetPort: 6379
    - name: cluster
      port: 16379
      targetPort: 16379
    # - name: metrics
    #   port: 9121
    #   targetPort: 9121
  type: ClusterIP
  sessionAffinity: None
