namespace: mongodb

resources:
  - ../../../../base/mongodb/plantsuite-psmdb

patches:
  - target:
      kind: PerconaServerMongoDB
      name: plantsuite-psmdb
    path: patches/plantsuite-psmdb-ops.yaml
  - target:
      kind: PerconaServerMongoDB
      name: plantsuite-psmdb
    path: patches/plantsuite-psmdb.yaml
