labels:
  - pairs:
      app: tenants
      app.kubernetes.io/name: tenants
    includeSelectors: true
    includeTemplates: true

resources:
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - hpa.yaml
  - pdb.yaml

configMapGenerator:
  - name: tenants-appsettings
    files:
      - appsettings.json

generatorOptions:
  disableNameSuffixHash: true
