labels:
  - pairs:
      app: notifications
      app.kubernetes.io/name: notifications
    includeSelectors: true
    includeTemplates: true

resources:
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - hpa.yaml

configMapGenerator:
  - name: notifications-appsettings
    files:
      - appsettings.json

generatorOptions:
  disableNameSuffixHash: true
