apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alarms
subjects:
  - kind: ServiceAccount
    name: alarms
roleRef:
  kind: Role
  name: alarms
  apiGroup: rbac.authorization.k8s.io
