apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: alarms
spec:
  hosts:
    - alarms.plantsuite.local
  gateways:
    - istio-ingress/gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 80
            host: alarms
