apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plantsuite

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - job.yaml
  - cronjob.yaml
